CREATE TABLE IF NOT EXISTS templates (
  id SERIAL PRIMARY KEY,
  title TEXT,
  username VARCHAR(256),
  date_created TEXT,
  template_1 TEXT,
  template_2 TEXT,
  template_3 TEXT,
  template_4 TEXT,
  template_5 TEXT,
  template_6 TEXT,
  template_7 TEXT,
  template_8 TEXT,
  template_9 TEXT,
  template_10 TEXT,
  template_11 TEXT,
  label_1 TEXT,
  label_2 TEXT,
  label_3 TEXT,
  label_4 TEXT,
  label_5 TEXT,
  label_6 TEXT,
  label_7 TEXT,
  label_8 TEXT,
  label_9 TEXT,
  label_10 TEXT,
  votes INT default 0
);

DELETE FROM templates;

INSERT INTO templates (
  title,
  username,
  date_created,
  template_1,
  template_2,
  template_3,
  template_4,
  template_5,
  template_6,
  template_7,
  template_8,
  template_9,
  template_10,
  template_11,
  label_1,
  label_2,
  label_3, 
  label_4,
  label_5,
  label_6,
  label_7,
  label_8,
  label_9,
  label_10
) VALUES (
  'Pick Up Lines',
  'adultmadlibs',
  '09/24/2018',
  'Is it ',
  ' in here, or is it just your ',
  '? Your ',
  ' must be real tired because you''ve been ',
  ' through my ',
  ' all night. ',
  ' does not respond to any of these pick up lines. ',
  ' grabs his/her/their ',
  ' and ',
  ' back ',
  '.',
  'adjective',
  'noun',
  'part of body',
  'verb ending in ing',
  'noun',
  'Name of a classmate',
  'prounoun of classmate',
  'noun',
  'verb',
  'noun'
);

INSERT INTO templates (
  title,
  username,
  date_created,
  template_1,
  template_2,
  template_3,
  template_4,
  template_5,
  template_6,
  template_7,
  template_8,
  template_9,
  template_10,
  template_11,
  label_1,
  label_2,
  label_3, 
  label_4,
  label_5,
  label_6,
  label_7,
  label_8,
  label_9,
  label_10
) VALUES (
'Strange News',
'Official',
'9/24/2018',
'A ',
' in ',
' was arresteed this morning after they ',
' in front of a ',
'. ',
', had a history of ',
', but no one, not even their ',
', would have imagined they''d ',
' with a ',
' stuck in their ',
'.',
'noun',
'state',
'past tense verb',
'noun',
'proper noun',
'verb',
'noun',
'verb',
'noun',
'body part'
);

-- INSERT INTO templates (
--   title,
--   username,
--   date_created,
--   template_1,
--   template_2,
--   template_3,
--   template_4,
--   template_5,
--   template_6,
--   template_7,
--   template_8,
--   template_9,
--   template_10,
--   template_11,
--   label_1,
--   label_2,
--   label_3, 
--   label_4,
--   label_5,
--   label_6,
--   label_7,
--   label_8,
--   label_9,
--   label_10
-- ) VALUES (
--   'Welcome to CodeLibs',
--   'Official',
--   '9/24/2018',
--   'Hi <$= lib_1 %>, welcome to <$= lib_2 %>, we are so <$= lib_3 %> to have you here! We hope you enjoy our <$= lib_4 %><$= lib_5 %>. Please feel free to <$= lib_6 %> the <$= lib_7 %> and dont forget to <$= lib_8 %>. We hope you have a <$= lib_9 %><$= lib_10 %>',
--   'name',
--   'location',
--   'adjective',
--   'adjective',
--   'noun',
--   'verb',
--   'noun',
--   'verb',
--   'adjective',
--   'noun'
-- );